services:
  goapp:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_DB=${REDIS_DB}
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
